[package]
name = "rain-tracker-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.7", features = ["any", "chrono", "macros", "runtime-tokio-rustls", "sqlite", "postgres"] }
serde_json = "1"
